[package]
name = "timber"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
pretty_env_logger = "0.5"
dotenv = "0.15.0"
anyhow = "1"
axum = "0.7"

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.timber-net]
path = "./timber-net"