[package]
name = "timber-net"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1"
serde_json = "1"
anyhow = "1"
thiserror = "1"
async-trait = "0.1"

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.serde]
version = "1"
features = ["derive"]